# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for composer
  - package-ecosystem: "composer"
    # Look for `composer.json` and `lock` files in the `root` directory
    directory: "/"
    # Check composer for updates every day (weekdays)
    schedule:
      interval: "monthly"
    reviewers:
      - "cmmata"
    commit-message:
      prefix: "composer prod"
      prefix-development: "composer dev"
      include: "scope"

  # Enable version updates for github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "cmmata"
    commit-message:
      prefix: "GA"
      include: "scope"
